name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    uses: NotThatJonSmith/Stella/.github/workflows/stella-project-ci.yml@main
