# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Mac OS Big Sur
            os: macos-11
          - name: Ubuntu
            os: ubuntu-latest
          - name: Windows Server
            os: windows-latest

    steps:

      - uses: actions/checkout@v2

      - name: Initialize submodules
        run: git submodule update --init

        # TODO make sure the build environment has a sane Python...

      - name: Bootstrap Ninja
        run: cd ninja && python configure.py --bootstrap

        # TODO install pip? Do we need to on any of the platforms?
        
      - name: Get GitPython
        run: pip install GitPython

      - name: Gather dependencies
        run: python ./Clumps/configure.py
          
      - name: Run the ninja build
        run: ./ninja/ninja
